### ISSUE TITLE
Platform error device_tracker.tplink_router - Integration 'tplink_router' not found

### ISSUE THREAD

**Issue by pex81** [ericpignet/home-assistant-tplink_router#41]
Hi, I wanted to try the integration with my TP Link Archer VR1200v but when after configuring the configuration.yaml the following error comes out.

```
device_tracker:
  - platform: tplink_router
    host: !secret tplink_router_ip
    username: !secret tplink_router_username
    password: !secret tplink_router_password
```
- Home Assistant 2022.3.1
 
<img width="638" alt="image" src="https://user-images.githubusercontent.com/58252398/156876593-83588869-1f70-477a-8d0f-54df03d4e783.png">
