### ISSUE TITLE
[VR600] logging out users from the Admin panel

### ISSUE THREAD

**Issue by GuyKh** [ericpignet/home-assistant-tplink_router#5]
When this integration runs, with VR600 and perhaps other routers, every time it logs in to the router to fetch existing users, it kicks out the logged in session from the admin page of the router (192.168.1.1)

One workaround is to increase the `interval_seconds` field
```
device_tracker:
  - platform: tplink_router
    host: IP_ADDRESS
    username: YOUR_USERNAME
    password: YOUR PASSWORD
    interval_seconds: 10 // <------- change this to 60 for once in every minute
```

I'll try to find a way to do that without kicking the user out - but just for you to know, this is a known issue
